### ISSUE TITLE
installation?

### ISSUE THREAD

**Issue by SpokieKid** [Darakah/obsidian-commits#1]
did you put this plugin off the market? What an awesome plugin!

**Comment by Darakah** [comment]
Hello! 
Glad you like the plugin! 

Waiting for the pull request to get accepted by the OB team so that it appears on the community tab inside Obsidian. Should take a day or two to go through.

Until then you can install it by downloading the latest release `main.js`, `style.css` & `manifest.json` from https://github.com/Darakah/obsidian-commits/releases/tag/0.2.2
Put all three files in a folder (call it something like `obsidian-commits` ... the name doesn't matter though), then place this folder inside the plugins folder of your vault. After that, refresh the plugins tab and it should appear there to be activated.

Let me know if you have any further questions.

Thanks for the STAR! greatly appreciated!!

**Comment by SpokieKid** [comment]
Thanks for the detailed installation guide. I've managed to put all the files in the correct place, but here comes another dumb question: How do I activate this plugin? I mean, where can i see the panel.

A good project like this deserves a star 👍

**Comment by Darakah** [comment]
Not sure which activation you are referring to:
- Obsidian settings (the gear Icon) -> Community plugins -> (if you have safe mode on you need to turn it off) -> it should appear under `Installed plugins` -> to the right there is a button when you click you can see it gets colored which means it got activates
- If you mean how to add the tags and track a specific project, please read the README (under usage), you have to use a code block renderer inside the note where you want to place it.
Let me know if you have any other questions

**Comment by SpokieKid** [comment]
I've figured out how to display the panels, but seems there's still one thing missing: the calendar view. What could be the reason?

**Comment by Darakah** [comment]
@SpokieKid , the activity board is a previous obsidian plugin of mine (https://github.com/Darakah/obsidian-activity-history)

This one you can already find in the community plugins list, just search activity and it should appear.

**Comment by SpokieKid** [comment]
Really appreciate the assistance, thanks!
